const HashMap = require("./HashMap")

const myHashMap = new HashMap()
myHashMap.set("apple", "red")
myHashMap.set("banana", "yellow")
myHashMap.set("carrot", "orange")
myHashMap.set("dog", "brown")
myHashMap.set("elephant", "gray")
myHashMap.set("frog", "green")
myHashMap.set("grape", "purple")
myHashMap.set("hat", "black")
myHashMap.set("ice cream", "white")
myHashMap.set("jacket", "blue")
myHashMap.set("kite", "pink")
myHashMap.set("lion", "golden")
console.log(myHashMap.length)
console.log(myHashMap.get("lion"))
myHashMap.set("lion", "rainbow")
console.log(myHashMap.get("lion"))
console.log(myHashMap.length)
console.log(myHashMap.buckets)
myHashMap.set("surf", "shark")
console.log(myHashMap.length)
console.log(myHashMap.buckets)
myHashMap.set("surf", "waves")
console.log(myHashMap.get("surf"))
console.log(myHashMap.has("surf") === true)
console.log(myHashMap.has("phone") === false)
myHashMap.remove("jacket")
console.log(myHashMap.has("jacket") === false)
console.log(myHashMap.keys())
console.log(myHashMap.values())
console.log(myHashMap.entries())
