const LinkedList = require("./linked-list")

const list = new LinkedList()

list.append("dog")
list.append("cat")
list.append("parrot")
list.prepend("snake")
console.log(list.toString())
console.log(list.size)
console.log(list.head.value)
console.log(list.tail.value)
console.log(list.at(1).value)
list.pop()
list.pop()
console.log(list.toString())
console.log(list.size)
console.log(list.contains("parrot"))
console.log(list.contains("dog"))
console.log(list.find("parrot"))
console.log(list.find("snake"))
list.insertAt("pig", 1)
console.log(list.toString())
list.removeAt(2)
console.log(list.toString())
